### PR TITLE
read key during cloudbuild

### PR DESCRIPTION
**Pull request by bolyachevets**

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://application-status-dev--pr-37-eijm4vfu.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://application-status-dev--pr-37-eijm4vfu.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://application-status-dev--pr-37-eijm4vfu.web.app

**Review by tronghieuvuong — APPROVED** [review]

**Pull request merged**
