### PR TITLE
Add hyperlinks to github issues.

### PR DESCRIPTION
**Pull request by tronghieuvuong**
1. Add hyperlink to github issues

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-14-52nrklyf.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-14-52nrklyf.web.app

**Review by pwei1018 — APPROVED** [review]

**Pull request merged**
