### PR TITLE
Fix API calling with different parameters

### PR DESCRIPTION
**Pull request by tronghieuvuong**
### Summary
Fetch 20 releases from Open/Closed state separately
https://app.zenhub.com/workspaces/ocm-team-space-5db37ce273e8f70001d9e2b1/issues/gh/bcgov-registries/ocm/1035

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-22-k0c8etr9.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-22-k0c8etr9.web.app

**Review by pwei1018 — APPROVED** [review]

**Pull request merged**
