### PR TITLE
Fix CD.

### PR DESCRIPTION
**Pull request by tronghieuvuong**
### Summary
Fix CD errors

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://application-status-dev--pr-47-7m5d7pbq.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-47-lezpj293.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://application-status-dev--pr-47-7m5d7pbq.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-47-lezpj293.web.app

**Review by bolyachevets — APPROVED** [review]

**Pull request merged**
