### PR TITLE
UI: Change font and text color.

### PR DESCRIPTION
**Pull request by tronghieuvuong**
### Summary
Change font and text color of Contact Card

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-26-qj155aki.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-26-qj155aki.web.app

**Review by pwei1018 — APPROVED** [review]

**Pull request merged**
