### PR TITLE
Tvuong/feat dropdownmenu

### PR DESCRIPTION
**Pull request by tronghieuvuong**
### Summary
Change the default state of the release page
Include drop down menu to direct to the correct state of releases

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-17-v9x14rc3.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-17-v9x14rc3.web.app

**Review by pwei1018 — APPROVED** [review]

**Pull request merged**
