### PR TITLE
Tvuong/feat tabs

### LINKED ISSUE #13: Display Closed and Open releases separately
### Summary
Add a button to change state for viewing CLOSED and OPEN releases separately

### PR DESCRIPTION
**Pull request by tronghieuvuong**
### Summary
1. Classify the content to closed and open releases to be easier to read
2. Manage state when user clicks on the button

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-12-megil1ya.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-12-megil1ya.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-12-megil1ya.web.app

**Review by pwei1018 — APPROVED** [review]

**Pull request merged**
