### PR TITLE
Add Paginations to move back and forth

### PR DESCRIPTION
**Pull request by tronghieuvuong**
### Summary
Add buttons for moving back and forth
https://app.zenhub.com/workspaces/ocm-team-space-5db37ce273e8f70001d9e2b1/issues/gh/bcgov-registries/ocm/1015

Navigate to specific release on the page when clicking on the date bookmarks
https://app.zenhub.com/workspaces/ocm-team-space-5db37ce273e8f70001d9e2b1/issues/gh/bcgov-registries/ocm/1017

Scroll to top when navigating to different pages
https://app.zenhub.com/workspaces/ocm-team-space-5db37ce273e8f70001d9e2b1/issues/gh/bcgov-registries/ocm/1026

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-21-4494xxp4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-21-4494xxp4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-21-4494xxp4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-21-4494xxp4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-21-4494xxp4.web.app

**Review by pwei1018 — APPROVED** [review]

**Pull request merged**
