### PR TITLE
Fixed the CD issue.

### PR DESCRIPTION
**Pull request by pwei1018**
1. Changed the actions/setup-node version from v1 to v3 in CI;
2. Added vault mapping;
3. Modified the preview site cloud build configuration to include environment variable;

### CODE REVIEW

**Review by tronghieuvuong — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://release-notes-dev--pr-9-nez74xja.web.app

**Comment by pwei1018** [comment]
@tronghieuvuong Preview site is up.

**Pull request merged**
